/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import javax.swing.JInternalFrame;

/**
 *
 * @author Mateus
 */
public class AD3Panel extends javax.swing.JFrame {

    /**
     * Creates new form AD3Panel
     */
    public AD3Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fundo_Titulo = new javax.swing.JPanel();
        Texto_Titulo = new javax.swing.JLabel();
        Fundo_Menu = new javax.swing.JPanel();
        Fundo_Menu_Topo = new javax.swing.JPanel();
        Menu_NomeCompleto = new javax.swing.JLabel();
        Menu_EMail = new javax.swing.JLabel();
        Botao_Configuracoes = new javax.swing.JButton();
        Botao_Inicio = new javax.swing.JButton();
        Botao_Denuncias = new javax.swing.JButton();
        Botao_Usuarios = new javax.swing.JButton();
        Botao_Sair = new javax.swing.JButton();
        Desktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setResizable(false);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        Fundo_Titulo.setBackground(new java.awt.Color(76, 175, 80));
        Fundo_Titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Texto_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Texto_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Texto_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_Titulo.setText("AD3Panel");

        javax.swing.GroupLayout Fundo_TituloLayout = new javax.swing.GroupLayout(Fundo_Titulo);
        Fundo_Titulo.setLayout(Fundo_TituloLayout);
        Fundo_TituloLayout.setHorizontalGroup(
            Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
            .addGroup(Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Fundo_TituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Texto_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Fundo_TituloLayout.setVerticalGroup(
            Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
            .addGroup(Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Fundo_TituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Texto_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(Fundo_Titulo);
        Fundo_Titulo.setBounds(0, 0, 600, 55);

        Fundo_Menu.setBackground(new java.awt.Color(204, 204, 204));
        Fundo_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Fundo_Menu.setLayout(null);

        Fundo_Menu_Topo.setBackground(new java.awt.Color(76, 175, 80));
        Fundo_Menu_Topo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Fundo_Menu_Topo.setForeground(new java.awt.Color(204, 204, 204));
        Fundo_Menu_Topo.setLayout(null);

        Menu_NomeCompleto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Menu_NomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        Menu_NomeCompleto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Menu_NomeCompleto.setText("Carregando...");
        Menu_NomeCompleto.setToolTipText("");
        Fundo_Menu_Topo.add(Menu_NomeCompleto);
        Menu_NomeCompleto.setBounds(10, 20, 180, 20);

        Menu_EMail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Menu_EMail.setForeground(new java.awt.Color(255, 255, 255));
        Menu_EMail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Menu_EMail.setText("Carregando...");
        Menu_EMail.setToolTipText("");
        Fundo_Menu_Topo.add(Menu_EMail);
        Menu_EMail.setBounds(10, 50, 180, 20);

        Fundo_Menu.add(Fundo_Menu_Topo);
        Fundo_Menu_Topo.setBounds(0, 0, 200, 100);

        Botao_Configuracoes.setBackground(new java.awt.Color(76, 175, 80));
        Botao_Configuracoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao_Configuracoes.setForeground(new java.awt.Color(255, 255, 255));
        Botao_Configuracoes.setText("Configurações");
        Botao_Configuracoes.setBorderPainted(false);
        Botao_Configuracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_ConfiguracoesActionPerformed(evt);
            }
        });
        Fundo_Menu.add(Botao_Configuracoes);
        Botao_Configuracoes.setBounds(20, 320, 150, 25);

        Botao_Inicio.setBackground(new java.awt.Color(76, 175, 80));
        Botao_Inicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao_Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Botao_Inicio.setText("Início");
        Botao_Inicio.setBorderPainted(false);
        Botao_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_InicioActionPerformed(evt);
            }
        });
        Fundo_Menu.add(Botao_Inicio);
        Botao_Inicio.setBounds(20, 140, 150, 25);

        Botao_Denuncias.setBackground(new java.awt.Color(76, 175, 80));
        Botao_Denuncias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao_Denuncias.setForeground(new java.awt.Color(255, 255, 255));
        Botao_Denuncias.setText("Denúncias");
        Botao_Denuncias.setBorderPainted(false);
        Botao_Denuncias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_DenunciasActionPerformed(evt);
            }
        });
        Fundo_Menu.add(Botao_Denuncias);
        Botao_Denuncias.setBounds(20, 200, 150, 25);

        Botao_Usuarios.setBackground(new java.awt.Color(76, 175, 80));
        Botao_Usuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao_Usuarios.setForeground(new java.awt.Color(255, 255, 255));
        Botao_Usuarios.setText("Usuários");
        Botao_Usuarios.setBorderPainted(false);
        Botao_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_UsuariosActionPerformed(evt);
            }
        });
        Fundo_Menu.add(Botao_Usuarios);
        Botao_Usuarios.setBounds(20, 260, 150, 25);

        Botao_Sair.setBackground(new java.awt.Color(244, 67, 54));
        Botao_Sair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao_Sair.setForeground(new java.awt.Color(255, 255, 255));
        Botao_Sair.setText("Sair");
        Botao_Sair.setBorderPainted(false);
        Botao_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_SairActionPerformed(evt);
            }
        });
        Fundo_Menu.add(Botao_Sair);
        Botao_Sair.setBounds(20, 410, 150, 25);

        getContentPane().add(Fundo_Menu);
        Fundo_Menu.setBounds(0, 55, 200, 450);

        Desktop.setBackground(new java.awt.Color(255, 255, 255));
        Desktop.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DesktopPropertyChange(evt);
            }
        });
        getContentPane().add(Desktop);
        Desktop.setBounds(200, 55, 400, 450);

        setSize(new java.awt.Dimension(616, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Inicio Inicio = new Inicio();
        Desktop.add(Inicio);
        Inicio.setLocation(-5, -25);
        Inicio.setVisible(true);
        MODEL.AD3Panel AD3Panel = new MODEL.AD3Panel();
        boolean Coletado = AD3Panel.SetarInfos();
        if(Coletado == true){
            Menu_EMail.setText(AD3Panel.getEMail());
            Menu_NomeCompleto.setText(AD3Panel.getNomeCompleto());
        } else {
            Menu_EMail.setText("E-Mail não localizado...");
            Menu_NomeCompleto.setText("Nome não localizado...");
        }
    }//GEN-LAST:event_formWindowOpened

    private void Botao_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_SairActionPerformed
        Entrar Entrar = new Entrar();
        this.dispose();
        Entrar.show();
    }//GEN-LAST:event_Botao_SairActionPerformed

    private void Botao_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_UsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Botao_UsuariosActionPerformed

    private void Botao_DenunciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_DenunciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Botao_DenunciasActionPerformed

    private void Botao_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_InicioActionPerformed
        Inicio Inicio = new Inicio();
        JInternalFrame Frame = Desktop.getSelectedFrame();
        
        if(Frame == null) {
            Desktop.add(Inicio);
            Inicio.setLocation(-5, -25);
            Inicio.setVisible(true);
        } else {
            Frame.dispose();
            Desktop.add(Inicio);
            Inicio.setLocation(-5, -25);
            Inicio.setVisible(true);
        }
    }//GEN-LAST:event_Botao_InicioActionPerformed

    private void Botao_ConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_ConfiguracoesActionPerformed
        Configuracoes Configuracoes = new Configuracoes();
        JInternalFrame Frame = Desktop.getSelectedFrame();
        if(Frame == null) {
            Desktop.add(Configuracoes);
            Configuracoes.setLocation(-5, -25);
            Configuracoes.setVisible(true);
        } else {
            Frame.dispose();
            Desktop.add(Configuracoes);
            Configuracoes.setLocation(-5, -25);
            Configuracoes.setVisible(true);
        }
    }//GEN-LAST:event_Botao_ConfiguracoesActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        MODEL.AD3Panel AD3Panel = new MODEL.AD3Panel();
        boolean Coletado = AD3Panel.SetarInfos();
        if(Coletado == true){
            Menu_EMail.setText(AD3Panel.getEMail());
            Menu_NomeCompleto.setText(AD3Panel.getNomeCompleto());
        } else {
            Menu_EMail.setText("E-Mail não localizado...");
            Menu_NomeCompleto.setText("Nome não localizado...");
        }
    }//GEN-LAST:event_formPropertyChange

    private void DesktopPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DesktopPropertyChange
        
    }//GEN-LAST:event_DesktopPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AD3Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AD3Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AD3Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AD3Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AD3Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_Configuracoes;
    private javax.swing.JButton Botao_Denuncias;
    private javax.swing.JButton Botao_Inicio;
    private javax.swing.JButton Botao_Sair;
    private javax.swing.JButton Botao_Usuarios;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JPanel Fundo_Menu;
    private javax.swing.JPanel Fundo_Menu_Topo;
    private javax.swing.JPanel Fundo_Titulo;
    public javax.swing.JLabel Menu_EMail;
    public javax.swing.JLabel Menu_NomeCompleto;
    private javax.swing.JLabel Texto_Titulo;
    // End of variables declaration//GEN-END:variables
}
