/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import javax.swing.JOptionPane;

/**
 *
 * @author Mateus
 */
public class Configuracoes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Configuracoes
     */
    public Configuracoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tela_Senha = new javax.swing.JDialog();
        Backrground = new javax.swing.JPanel();
        Campo_Senha = new javax.swing.JPasswordField();
        Texto_Senha = new javax.swing.JLabel();
        Botao_Cancelar_Senha = new javax.swing.JButton();
        Botao_Confirmar_Senha = new javax.swing.JButton();
        Fundo_Titulo = new javax.swing.JPanel();
        Texto_Titulo = new javax.swing.JLabel();
        Texto_Titulo_InformacoesLogin = new javax.swing.JLabel();
        Texto_NomeCompleto = new javax.swing.JLabel();
        Campo_NomeCompleto = new javax.swing.JTextField();
        Texto_EMail = new javax.swing.JLabel();
        Campo_Email = new javax.swing.JTextField();
        Texto_Titulo_InformacoesPessoais = new javax.swing.JLabel();
        Texto_CPF = new javax.swing.JLabel();
        Campo_CPF = new javax.swing.JFormattedTextField();
        Campo_RG = new javax.swing.JFormattedTextField();
        Texto_RG = new javax.swing.JLabel();
        Texto_Endereco = new javax.swing.JLabel();
        Campo_Endereco = new javax.swing.JTextField();
        Texto_Telefone = new javax.swing.JLabel();
        Campo_Telefone = new javax.swing.JFormattedTextField();
        Botao_Salvar = new javax.swing.JButton();
        Botao_Cancelar = new javax.swing.JButton();

        Tela_Senha.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Tela_Senha.setTitle("Insira sua senha!");
        Tela_Senha.setBackground(new java.awt.Color(204, 204, 204));
        Tela_Senha.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        Tela_Senha.setLocation(new java.awt.Point(0, 0));
        Tela_Senha.setUndecorated(true);
        Tela_Senha.setPreferredSize(new java.awt.Dimension(300, 95));
        Tela_Senha.setSize(new java.awt.Dimension(300, 95));
        Tela_Senha.setType(java.awt.Window.Type.POPUP);
        Tela_Senha.getContentPane().setLayout(null);

        Backrground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Backrground.setLayout(null);

        Campo_Senha.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Campo_Senha.setToolTipText("Senha");
        Backrground.add(Campo_Senha);
        Campo_Senha.setBounds(20, 30, 260, 20);

        Texto_Senha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Texto_Senha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_Senha.setText("Insira sua senha para salvar!");
        Backrground.add(Texto_Senha);
        Texto_Senha.setBounds(0, 0, 300, 30);

        Botao_Cancelar_Senha.setBackground(new java.awt.Color(244, 67, 54));
        Botao_Cancelar_Senha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Botao_Cancelar_Senha.setForeground(new java.awt.Color(255, 255, 255));
        Botao_Cancelar_Senha.setText("CANCELAR");
        Botao_Cancelar_Senha.setBorder(null);
        Botao_Cancelar_Senha.setBorderPainted(false);
        Botao_Cancelar_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Cancelar_SenhaActionPerformed(evt);
            }
        });
        Backrground.add(Botao_Cancelar_Senha);
        Botao_Cancelar_Senha.setBounds(190, 60, 80, 20);

        Botao_Confirmar_Senha.setBackground(new java.awt.Color(76, 175, 80));
        Botao_Confirmar_Senha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Botao_Confirmar_Senha.setForeground(new java.awt.Color(255, 255, 255));
        Botao_Confirmar_Senha.setText("CONFIRMAR");
        Botao_Confirmar_Senha.setBorder(null);
        Botao_Confirmar_Senha.setBorderPainted(false);
        Botao_Confirmar_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Confirmar_SenhaActionPerformed(evt);
            }
        });
        Backrground.add(Botao_Confirmar_Senha);
        Botao_Confirmar_Senha.setBounds(30, 60, 80, 20);

        Tela_Senha.getContentPane().add(Backrground);
        Backrground.setBounds(0, 0, 300, 95);

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Configurações");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        Fundo_Titulo.setBackground(new java.awt.Color(76, 175, 80));
        Fundo_Titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Texto_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Texto_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Texto_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_Titulo.setText("Configurações");
        Texto_Titulo.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout Fundo_TituloLayout = new javax.swing.GroupLayout(Fundo_Titulo);
        Fundo_Titulo.setLayout(Fundo_TituloLayout);
        Fundo_TituloLayout.setHorizontalGroup(
            Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Fundo_TituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Texto_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Fundo_TituloLayout.setVerticalGroup(
            Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
            .addGroup(Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Fundo_TituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Texto_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(Fundo_Titulo);
        Fundo_Titulo.setBounds(0, 0, 400, 40);

        Texto_Titulo_InformacoesLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Texto_Titulo_InformacoesLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_Titulo_InformacoesLogin.setText("Informações de Login");
        Texto_Titulo_InformacoesLogin.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Texto_Titulo_InformacoesLogin);
        Texto_Titulo_InformacoesLogin.setBounds(0, 40, 400, 22);

        Texto_NomeCompleto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Texto_NomeCompleto.setText("Nome Completo");
        getContentPane().add(Texto_NomeCompleto);
        Texto_NomeCompleto.setBounds(10, 70, 140, 17);

        Campo_NomeCompleto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Campo_NomeCompleto.setToolTipText("Nome Completo");
        getContentPane().add(Campo_NomeCompleto);
        Campo_NomeCompleto.setBounds(10, 90, 230, 20);

        Texto_EMail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Texto_EMail.setText("E-Mail");
        getContentPane().add(Texto_EMail);
        Texto_EMail.setBounds(10, 120, 50, 17);

        Campo_Email.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Campo_Email.setToolTipText("E-Mail");
        getContentPane().add(Campo_Email);
        Campo_Email.setBounds(10, 140, 230, 20);

        Texto_Titulo_InformacoesPessoais.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Texto_Titulo_InformacoesPessoais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_Titulo_InformacoesPessoais.setText("Informações Pessoais");
        Texto_Titulo_InformacoesPessoais.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Texto_Titulo_InformacoesPessoais);
        Texto_Titulo_InformacoesPessoais.setBounds(0, 180, 390, 22);

        Texto_CPF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Texto_CPF.setText("CPF");
        getContentPane().add(Texto_CPF);
        Texto_CPF.setBounds(10, 210, 80, 17);

        try {
            Campo_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Campo_CPF.setText("");
        Campo_CPF.setToolTipText("CPF");
        Campo_CPF.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(Campo_CPF);
        Campo_CPF.setBounds(10, 230, 80, 20);

        try {
            Campo_RG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Campo_RG.setText("");
        Campo_RG.setToolTipText("RG");
        Campo_RG.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(Campo_RG);
        Campo_RG.setBounds(120, 230, 80, 20);

        Texto_RG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Texto_RG.setText("RG");
        getContentPane().add(Texto_RG);
        Texto_RG.setBounds(120, 210, 80, 17);

        Texto_Endereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Texto_Endereco.setText("Endereço");
        getContentPane().add(Texto_Endereco);
        Texto_Endereco.setBounds(10, 260, 80, 17);

        Campo_Endereco.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Campo_Endereco.setToolTipText("Endereço");
        getContentPane().add(Campo_Endereco);
        Campo_Endereco.setBounds(10, 280, 230, 20);

        Texto_Telefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Texto_Telefone.setText("Telefone");
        getContentPane().add(Texto_Telefone);
        Texto_Telefone.setBounds(10, 310, 80, 17);

        try {
            Campo_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+55 (##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Campo_Telefone.setToolTipText("RG");
        Campo_Telefone.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(Campo_Telefone);
        Campo_Telefone.setBounds(10, 330, 230, 20);

        Botao_Salvar.setBackground(new java.awt.Color(76, 175, 80));
        Botao_Salvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Botao_Salvar.setForeground(new java.awt.Color(255, 255, 255));
        Botao_Salvar.setText("SALVAR");
        Botao_Salvar.setBorderPainted(false);
        Botao_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(Botao_Salvar);
        Botao_Salvar.setBounds(50, 390, 100, 20);

        Botao_Cancelar.setBackground(new java.awt.Color(244, 67, 54));
        Botao_Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Botao_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Botao_Cancelar.setText("Cancelar");
        Botao_Cancelar.setBorderPainted(false);
        Botao_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Botao_Cancelar);
        Botao_Cancelar.setBounds(240, 390, 100, 20);

        setBounds(1, 1, 410, 485);
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_SalvarActionPerformed
        Tela_Senha.setLocationRelativeTo(null);
        MODEL.AD3Panel AD3Panel = new MODEL.AD3Panel();
        MODEL.Configuracoes Configuracoes = new MODEL.Configuracoes();
        String Email = Campo_Email.getText().toString();
        String Senha = Campo_Senha.getText().toString();
        String NomeCompleto = Campo_NomeCompleto.getText().toString();
        String CPF = Campo_CPF.getText().toString();
        String RG = Campo_RG.getText().toString();
        String Endereco = Campo_Endereco.getText().toString();
        String Telefone = Campo_Telefone.getText().toString();
        if(Email.equals("") || NomeCompleto.equals("") || CPF.equals("") || RG.equals("") || Endereco.equals("") || Telefone.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Erro", JOptionPane.WARNING_MESSAGE);
        } else {
            Tela_Senha.show();
        }
    }//GEN-LAST:event_Botao_SalvarActionPerformed

    private void Botao_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_CancelarActionPerformed
        MODEL.Configuracoes Configuracoes = new MODEL.Configuracoes();
        boolean Coletado =  Configuracoes.SetarInfos();
        if(Coletado == true){
            Campo_Email.setText(Configuracoes.getEmail());
            Campo_NomeCompleto.setText(Configuracoes.getNomeCompleto());
            Campo_CPF.setText(Configuracoes.getCPF());
            Campo_RG.setText(Configuracoes.getRG());
            Campo_Endereco.setText(Configuracoes.getEndereco());
            Campo_Telefone.setText(Configuracoes.getTelefone());
        } else{
            JOptionPane.showMessageDialog(null, "Erro ao localizar os dados, tente novamente mais tarde!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Botao_CancelarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        MODEL.Configuracoes Configuracoes = new MODEL.Configuracoes();
        boolean Coletado =  Configuracoes.SetarInfos();
        if(Coletado == true){
            Campo_Email.setText(Configuracoes.getEmail());
            Campo_NomeCompleto.setText(Configuracoes.getNomeCompleto());
            Campo_CPF.setText(Configuracoes.getCPF());
            Campo_RG.setText(Configuracoes.getRG());
            Campo_Endereco.setText(Configuracoes.getEndereco());
            Campo_Telefone.setText(Configuracoes.getTelefone());
        } else{
            JOptionPane.showMessageDialog(null, "Erro ao localizar os dados, tente novamente mais tarde!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void Botao_Cancelar_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Cancelar_SenhaActionPerformed
        Tela_Senha.dispose();
        MODEL.Configuracoes Configuracoes = new MODEL.Configuracoes();
        boolean Coletado =  Configuracoes.SetarInfos();
        if(Coletado == true){
            Campo_Email.setText(Configuracoes.getEmail());
            Campo_NomeCompleto.setText(Configuracoes.getNomeCompleto());
            Campo_CPF.setText(Configuracoes.getCPF());
            Campo_RG.setText(Configuracoes.getRG());
            Campo_Endereco.setText(Configuracoes.getEndereco());
            Campo_Telefone.setText(Configuracoes.getTelefone());
        } else{
            JOptionPane.showMessageDialog(null, "Erro ao localizar os dados, tente novamente mais tarde!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Botao_Cancelar_SenhaActionPerformed

    private void Botao_Confirmar_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Confirmar_SenhaActionPerformed
        MODEL.AD3Panel AD3Panel = new MODEL.AD3Panel();
        MODEL.Configuracoes Configuracoes = new MODEL.Configuracoes();
        String Email = Campo_Email.getText().toString();
        String Senha = Campo_Senha.getText().toString();
        String NomeCompleto = Campo_NomeCompleto.getText().toString();
        String CPF = Campo_CPF.getText().toString();
        String RG = Campo_RG.getText().toString();
        String Endereco = Campo_Endereco.getText().toString();
        String Telefone = Campo_Telefone.getText().toString();
        if(Senha.equals("")){
                JOptionPane.showMessageDialog(null, "Insira sua senha para salvar!", "Erro", JOptionPane.WARNING_MESSAGE);
            } else{
                JOptionPane.showMessageDialog(null, "Aguarde as informações serem verificadas!", "Verificando Informações...", JOptionPane.WARNING_MESSAGE);
                boolean VerificarInfos = Configuracoes.VerificarInfos(Email, CPF, RG, Telefone, AD3Panel.getID(), Senha);
                if(VerificarInfos == true){
                    boolean AtualizarInfos = Configuracoes.AtualizarInfos(NomeCompleto, Email, CPF, RG, Endereco, Telefone, AD3Panel.getID());
                    if(AtualizarInfos == true){
                        boolean Coletado =  Configuracoes.SetarInfos();
                        if(Coletado == true){
                            AD3Panel.setEMail(Configuracoes.getEmail());
                            AD3Panel.setNomeCompleto(Configuracoes.getNomeCompleto());
                            Campo_Email.setText(Configuracoes.getEmail());
                            Campo_NomeCompleto.setText(Configuracoes.getNomeCompleto());
                            Campo_CPF.setText(Configuracoes.getCPF());
                            Campo_RG.setText(Configuracoes.getRG());
                            Campo_Endereco.setText(Configuracoes.getEndereco());
                            Campo_Telefone.setText(Configuracoes.getTelefone());
                            Campo_Senha.setText("");
                            Tela_Senha.dispose();
                            JOptionPane.showMessageDialog(null, "Informações atualizadas com sucesso!\nPor segurança recomendamos sair e entrar novamente!", "Status", JOptionPane.INFORMATION_MESSAGE);
                        } else{
                            JOptionPane.showMessageDialog(null, "Erro ao localizar os dados, tente novamente mais tarde!", "Erro", JOptionPane.ERROR_MESSAGE);
                        }
                    } else{
                        JOptionPane.showMessageDialog(null, "Ocorreu um erro, tente novamente!", "Status", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
    }//GEN-LAST:event_Botao_Confirmar_SenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backrground;
    private javax.swing.JButton Botao_Cancelar;
    private javax.swing.JButton Botao_Cancelar_Senha;
    private javax.swing.JButton Botao_Confirmar_Senha;
    private javax.swing.JButton Botao_Salvar;
    public javax.swing.JFormattedTextField Campo_CPF;
    public javax.swing.JTextField Campo_Email;
    public javax.swing.JTextField Campo_Endereco;
    public javax.swing.JTextField Campo_NomeCompleto;
    public javax.swing.JFormattedTextField Campo_RG;
    public javax.swing.JPasswordField Campo_Senha;
    public javax.swing.JFormattedTextField Campo_Telefone;
    private javax.swing.JPanel Fundo_Titulo;
    public javax.swing.JDialog Tela_Senha;
    private javax.swing.JLabel Texto_CPF;
    private javax.swing.JLabel Texto_EMail;
    private javax.swing.JLabel Texto_Endereco;
    private javax.swing.JLabel Texto_NomeCompleto;
    private javax.swing.JLabel Texto_RG;
    private javax.swing.JLabel Texto_Senha;
    private javax.swing.JLabel Texto_Telefone;
    private javax.swing.JLabel Texto_Titulo;
    private javax.swing.JLabel Texto_Titulo_InformacoesLogin;
    private javax.swing.JLabel Texto_Titulo_InformacoesPessoais;
    // End of variables declaration//GEN-END:variables
}
