/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import javax.swing.JOptionPane;

/**
 *
 * @author Mateus
 */
public class Entrar extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public Entrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fundo_Titulo = new javax.swing.JPanel();
        Texto_Titulo = new javax.swing.JLabel();
        Texto_EMail = new javax.swing.JLabel();
        Campo_Email = new javax.swing.JTextField();
        Texto_Senha = new javax.swing.JLabel();
        Campo_Senha = new javax.swing.JPasswordField();
        Botao_Login = new javax.swing.JButton();
        Botao_Registro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entrar");
        setResizable(false);
        getContentPane().setLayout(null);

        Fundo_Titulo.setBackground(new java.awt.Color(76, 175, 80));

        Texto_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Texto_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Texto_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_Titulo.setText("ENTRAR");

        javax.swing.GroupLayout Fundo_TituloLayout = new javax.swing.GroupLayout(Fundo_Titulo);
        Fundo_Titulo.setLayout(Fundo_TituloLayout);
        Fundo_TituloLayout.setHorizontalGroup(
            Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Fundo_TituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Texto_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Fundo_TituloLayout.setVerticalGroup(
            Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
            .addGroup(Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Fundo_TituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Texto_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(Fundo_Titulo);
        Fundo_Titulo.setBounds(0, 0, 600, 55);

        Texto_EMail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Texto_EMail.setText("E-Mail");
        getContentPane().add(Texto_EMail);
        Texto_EMail.setBounds(180, 160, 70, 22);

        Campo_Email.setToolTipText("E-Mail");
        getContentPane().add(Campo_Email);
        Campo_Email.setBounds(180, 180, 250, 30);

        Texto_Senha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Texto_Senha.setText("Senha");
        getContentPane().add(Texto_Senha);
        Texto_Senha.setBounds(180, 240, 70, 22);

        Campo_Senha.setToolTipText("Senha");
        getContentPane().add(Campo_Senha);
        Campo_Senha.setBounds(180, 260, 250, 30);

        Botao_Login.setBackground(new java.awt.Color(76, 175, 80));
        Botao_Login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao_Login.setForeground(new java.awt.Color(255, 255, 255));
        Botao_Login.setText("ENTRAR");
        Botao_Login.setBorderPainted(false);
        Botao_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Botao_Login);
        Botao_Login.setBounds(220, 320, 150, 25);

        Botao_Registro.setBackground(new java.awt.Color(244, 67, 54));
        Botao_Registro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao_Registro.setForeground(new java.awt.Color(255, 255, 255));
        Botao_Registro.setText("REGISTRAR-SE");
        Botao_Registro.setBorderPainted(false);
        Botao_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_RegistroActionPerformed(evt);
            }
        });
        getContentPane().add(Botao_Registro);
        Botao_Registro.setBounds(220, 350, 150, 25);

        setSize(new java.awt.Dimension(616, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_RegistroActionPerformed
        Registro Registro = new Registro();
        this.dispose();
        Registro.show();
    }//GEN-LAST:event_Botao_RegistroActionPerformed

    private void Botao_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_LoginActionPerformed
        MODEL.Entrar Entrar = new MODEL.Entrar();
        String Email = Campo_Email.getText().toString();
        String Senha = Campo_Senha.getText().toString();
        
        if(Email.equals("") || Senha.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Erro", JOptionPane.WARNING_MESSAGE);
        } else {
            String ID = Entrar.Entrar(Email, Senha);
            if(!ID.equals("")){
                MODEL.AD3Panel ModelPrincipal = new MODEL.AD3Panel();
                ModelPrincipal.setID(ID);
                this.dispose();
                AD3Panel Principal = new AD3Panel();
                Principal.show();
            }
        }
    }//GEN-LAST:event_Botao_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_Login;
    private javax.swing.JButton Botao_Registro;
    private javax.swing.JTextField Campo_Email;
    private javax.swing.JPasswordField Campo_Senha;
    private javax.swing.JPanel Fundo_Titulo;
    private javax.swing.JLabel Texto_EMail;
    private javax.swing.JLabel Texto_Senha;
    private javax.swing.JLabel Texto_Titulo;
    // End of variables declaration//GEN-END:variables
}
