
package VIEW;

import DAO.ConfiguracoesDAO;
import javax.swing.JOptionPane;

public class InicioColaborador extends javax.swing.JFrame {

    public InicioColaborador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Texto_BemVindo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        b_configs = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(350, 0), new java.awt.Dimension(350, 0), new java.awt.Dimension(350, 32767));
        Texto_BemVindo1 = new javax.swing.JLabel();
        b_gerenciardenuncia = new javax.swing.JButton();
        b_gerenciarusuarios = new javax.swing.JButton();
        b_gerenciarcodigos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Aglomerações");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        Texto_BemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_BemVindo.setText("Bem vindo(a) NOMECOMPLETO, você entrou com o e-mail EMAIL!");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aqui você poderá gerenciar as denuncias!");

        b_configs.setText("Configurações");
        b_configs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_configsActionPerformed(evt);
            }
        });

        Texto_BemVindo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_BemVindo1.setText("Você tem o nível de acesso NIVELACESSO!");

        b_gerenciardenuncia.setText("Gerenciar Denuncias");
        b_gerenciardenuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_gerenciardenunciaActionPerformed(evt);
            }
        });

        b_gerenciarusuarios.setText("Gerenciar Usuários");
        b_gerenciarusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_gerenciarusuariosActionPerformed(evt);
            }
        });

        b_gerenciarcodigos.setText("Gerenciar Códigos");
        b_gerenciarcodigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_gerenciarcodigosActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Texto_BemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Texto_BemVindo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_gerenciardenuncia)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_configs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_gerenciarusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(b_gerenciarcodigos)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Texto_BemVindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Texto_BemVindo1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_gerenciardenuncia)
                    .addComponent(b_gerenciarusuarios)
                    .addComponent(b_gerenciarcodigos))
                .addGap(30, 30, 30)
                .addComponent(b_configs)
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void b_gerenciardenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_gerenciardenunciaActionPerformed
        this.setVisible(false);
        GerenciarDenuncias GerenciarDenuncias = new GerenciarDenuncias();
        GerenciarDenuncias.setVisible(true);
    }//GEN-LAST:event_b_gerenciardenunciaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Login Login = new Login();
        MODEL.LoginM LoginM = new MODEL.LoginM();
        CONTROLLER.InicioColaboradorC InicioColaboradorC = new CONTROLLER.InicioColaboradorC();
        
        boolean Verificado = InicioColaboradorC.AtualizarDados();
        
        if(Verificado == true){
            if(LoginM.getNivelAcesso() == 1){
                b_gerenciardenuncia.setVisible(false);
                b_gerenciarusuarios.setVisible(false);
                b_gerenciarcodigos.setVisible(false);
                
                this.dispose();
                Login.show();
                JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esta página!\nEntre em sua conta novamente!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            if(LoginM.getNivelAcesso() == 2){
                b_gerenciardenuncia.setVisible(true);
                b_gerenciarusuarios.setVisible(false);
                b_gerenciarcodigos.setVisible(false);
            }
            if(LoginM.getNivelAcesso() == 3){
                b_gerenciardenuncia.setVisible(true);
                b_gerenciarusuarios.setVisible(true);
                b_gerenciarcodigos.setVisible(false);
            }
            if(LoginM.getNivelAcesso() >= 4){
                b_gerenciardenuncia.setVisible(true);
                b_gerenciarusuarios.setVisible(true);
                b_gerenciarcodigos.setVisible(true);
            }
        }
        
        String Texto1 = Texto_BemVindo.getText();
        String Texto2 = Texto_BemVindo1.getText();
        
        Texto1 = Texto1.replaceAll("NOMECOMPLETO", LoginM.getNomeCompleto());
        Texto1 = Texto1.replaceAll("EMAIL", LoginM.getEMail());
        Texto2 = Texto2.replaceAll("NIVELACESSO", Integer.toString(LoginM.getNivelAcesso()));
        
        Texto_BemVindo.setText(Texto1);
        Texto_BemVindo1.setText(Texto2);
    }//GEN-LAST:event_formWindowOpened

    private void b_configsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_configsActionPerformed
        Configuracoes Configuracoes = new Configuracoes();
        this.dispose();
        Configuracoes.setVisible(true);
    }//GEN-LAST:event_b_configsActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Login Login = new Login();
        this.dispose();
        Login.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void b_gerenciarusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_gerenciarusuariosActionPerformed
        GerenciarUsuarios GerenciarUsuarios = new GerenciarUsuarios();
        this.dispose();
        GerenciarUsuarios.setVisible(true);
    }//GEN-LAST:event_b_gerenciarusuariosActionPerformed

    private void b_gerenciarcodigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_gerenciarcodigosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_gerenciarcodigosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        b_gerenciardenuncia.setVisible(false);
        b_gerenciarusuarios.setVisible(false);
        b_gerenciarcodigos.setVisible(false);
    }//GEN-LAST:event_formWindowStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioColaborador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Texto_BemVindo;
    private javax.swing.JLabel Texto_BemVindo1;
    private javax.swing.JButton b_configs;
    private javax.swing.JButton b_gerenciarcodigos;
    private javax.swing.JButton b_gerenciardenuncia;
    private javax.swing.JButton b_gerenciarusuarios;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
